---
- name: Create a resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"

- name: Create storage account
  azure.azcollection.azure_rm_storageaccount:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_storage_account_name }}"
    type: "{{ azure_storage_account_type }}"
  register: azure_storage_account_result

- name: Create storage container
  azure.azcollection.azure_rm_storageblob:
    resource_group: "{{ azure_resource_group }}"
    storage_account_name: "{{ azure_storage_account_name }}"
    container: "{{ azure_storage_container_name }}"

- name: Get connection key
  azure.azcollection.azure_rm_storageaccount_info:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_storage_account_name }}"
    show_connection_string: true
  register: azure_storage_account_info

- name: Output connection key
  ansible.builtin.debug:
    msg: "Connection key for composer variable: {{ azure_storage_account_info.storageaccounts[0].primary_endpoints.key }}"
