---
# Path where osbuild contents will be pushed.
composer_osbuild_workdir: /tmp/osbuild-aap

# The AAP version that will be used when using AAP repositories.
composer_aap_version: "2.4"

# The RHEL version that will be used when enabling AAP repos.  Defaults to the host's version.
composer_rhel_version: "{{ ansible_facts['distribution_major_version'] }}"

# RHEL version override.  See `composer-cli distros list` for options on the builder host machine.
composer_rhel_distro: ""

# Ansible RPM Name
composer_ansible_rpm: "ansible-automation-platform-{{ composer_aap_version }}-for-rhel-{{ composer_rhel_version }}-{{ ansible_facts['architecture'] }}-rpms"

# Location for Podman auth file.
composer_podman_auth_file_location: /etc/osbuild-worker/containers-auth.json

# Semantic version start for image builds.
composer_build_image_version: "1.0.0"

# The size of the VM image when output.  Clouds will resize the drive on initial boot.  Not setting this will default to 10 GB.
composer_build_image_size: "4096"

# Enables the EPEL repo during build and in the resulting image.
composer_add_epel_repo: false

# Array of clouds to build images for.  The presence of a cloud requires the proper blueprint and auth files.
composer_clouds:
  - name: azure
    image_format: vhd
  - name: aws
    image_format: ami

# The storage container name that will be used to push Azure images.
composer_azure_storage_container_name: vmimagecontainer

# The S3 details used to push AWS images.
composer_aws_region: us-east-1
composer_aws_bucket: vm-image-imports
composer_aws_image_key: "aap-installer-rhel-9-{{ lookup('pipe', 'date +%s') }}"
