---
# Timestamp that can be used to identify builds
composer_timestamp: "{{ lookup('pipe', 'date +%s') }}"

# Path where osbuild contents will be pushed.
composer_osbuild_workdir: /etc/osbuild-composer/osbuild-aap

# The AAP version that will be used when using AAP repositories.
composer_aap_version: "2.4"

# The RHEL version that will be used when enabling AAP repos.  Defaults to the host's version.
composer_rhel_version: "{{ ansible_facts['distribution_major_version'] }}"

# Default name for images
composer_image_key: "aap-installer-rhel{{ composer_rhel_version }}-{{ ansible_facts['architecture'] }}-{{ composer_timestamp }}"

# RHEL version override.  See `composer-cli distros list` for options on the builder host machine.
composer_rhel_distro: ""

# Ansible RPM Name
composer_ansible_rpm: "ansible-automation-platform-{{ composer_aap_version }}-for-rhel-{{ composer_rhel_version }}-{{ ansible_facts['architecture'] }}-rpms"

# Location for Podman auth file.
composer_podman_auth_file_location: /etc/osbuild-worker/containers-auth.json

# Semantic version start for image builds.
composer_build_image_version: "1.0.0"

# The size of the VM image when output.  Clouds will resize the drive on initial boot.  Not setting this will default to 10 GB.
composer_build_image_size: "4096"

# Enables the EPEL repo during build and in the resulting image.
composer_add_epel_repo: false

# Array of clouds to build images. The presence of a cloud requires the proper blueprint, auth files, and variables for those files. Leaving these defaults as is will result in build failures.  All variables are required for a given cloud.  You may delete a full cloud entry to omit it.
composer_clouds:
  - name: azure
    image_format: vhd
    storage_container_name:
    storage_account_name:
    storage_account_access_key:
  - name: aws
    image_format: ami
    region: us-east-1
    bucket:
    image_key: "{{ composer_image_key }}"
    access_key_id:
    secret_access_key:
    session_token:
  - name: gcp
    image_format: gce
    bucket:
    region: us-east1
    image_key: "{{ composer_image_key | replace('_', '-') }}"
    credentials:
  - name: oci
    image_format: oci
    user:
    tenancy:
    fingerprint:
    region: us-ashburn-1
    bucket:
    namespace:
    compartment:
    private_key:
