objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    repo_info:
      description: Retrieves information about repositories managed by subscription
        manager.
      name: repo_info
      namespace: ''
      version_added: 1.1.1
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.1.1
