---
objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    gpg_file_info:
      description: Retrieves GPG keys from files on Linux systems.
      name: gpg_file_info
      namespace: ''
      version_added: 1.1.2
    repo_info:
      description: Retrieves information about repositories managed by subscription manager.
      name: repo_info
      namespace: ''
      version_added: 1.1.1
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.1.5
