---
- name: Assert that Azure credentials exist
  ansible.builtin.assert:
    that:
      - composer_azure_storage_account_name is defined
      - composer_azure_storage_account_access_key is defined
      - composer_azure_storage_container_name is defined
  when: cloud == 'azure'

- name: Assert that AWS credentials exist
  ansible.builtin.assert:
    that:
      - composer_aws_access_key_id is defined
      - composer_aws_secret_access_key is defined
      - composer_aws_session_token is defined
  when: cloud == 'aws'

- name: Create credential toml file
  ansible.builtin.template:
    src: "{{ cloud }}/config.j2"
    dest: "{{ composer_osbuild_workdir }}/{{ cloud }}-config.toml"
    mode: '0644'
