---
- name: Create osbuild source directory
  ansible.builtin.file:
    path: "{{ composer_osbuild_workdir }}"
    state: directory
    mode: "0770"

- name: Create directory /etc/osbuild-composer/repositories/
  ansible.builtin.file:
    path: /etc/osbuild-composer/repositories/
    state: directory
    mode: "0775"
    recurse: true
