---
- name: Assert that required variables are set
  ansible.builtin.assert:
    that:
      - podman_username is defined
      - podman_password is defined

- name: Create required directories
  ansible.builtin.import_tasks: directories.yml

- name: Setup build RPM repositories
  ansible.builtin.import_tasks: rpm_repositories.yml

- name: Setup build container registries
  ansible.builtin.import_tasks: container_registries.yml

- name: Create osbuild blueprints
  vars:
    composer_build_name: "{{ item.name }}"
  ansible.builtin.include_tasks: blueprint.yml
  loop: "{{ composer_clouds }}"

- name: Create credentials files
  vars:
    cloud: "{{ item.name }}"
  ansible.builtin.include_tasks: credentials.yml
  loop: "{{ composer_clouds }}"

- name: Build image
  vars:
    cloud: "{{ item }}"
  ansible.builtin.include_tasks: build.yml
  loop: "{{ composer_clouds }}"
