---
# Setup the storage resources in AWS to push images to.
- name: Setup AWS account resources
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Import aws role
      ansible.builtin.import_role:
        name: aws
