---
# Runs the process of building VM images
- name: Build VM images
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Import composer role
      ansible.builtin.import_role:
        name: composer
