---
# Runs the process of configuring osbuild and building VM images.
# This will override existing osbuild configurations for the files
# that are created with this role.
- name: Configure osbuild and build images
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Import composer role
      ansible.builtin.import_role:
        name: composer
