---
# Prepares the build RHEL host with necessary dependencies.
- name: Setup hosts
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Run setup hosts role
      ansible.builtin.import_role:
        name: lab.osbuild.host_setup
